/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as MarketingBrandRouteImport } from './routes/_marketing.brand'
import { Route as MarketingCompanyRouteImport } from './routes/_marketing.company'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingCustomersRouteImport } from './routes/_marketing.customers'
import { Route as MarketingHelpRouteImport } from './routes/_marketing.help'
import { Route as MarketingIntegrationsRouteImport } from './routes/_marketing.integrations'
import { Route as MarketingOpenRouteImport } from './routes/_marketing.open'
import { Route as MarketingOssFriendsRouteImport } from './routes/_marketing.oss-friends'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing.blog.index'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing.blog.$slug'
import { Route as MarketingBlogCategorySlugRouteImport } from './routes/_marketing.blog.category.$slug'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBrandRoute = MarketingBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCompanyRoute = MarketingCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCustomersRoute = MarketingCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHelpRoute = MarketingHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingIntegrationsRoute = MarketingIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOpenRoute = MarketingOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOssFriendsRoute = MarketingOssFriendsRouteImport.update({
  id: '/oss-friends',
  path: '/oss-friends',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogCategorySlugRoute =
  MarketingBlogCategorySlugRouteImport.update({
    id: '/blog/category/$slug',
    path: '/blog/category/$slug',
    getParentRoute: () => MarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/about': typeof MarketingAboutRoute
  '/brand': typeof MarketingBrandRoute
  '/company': typeof MarketingCompanyRoute
  '/contact': typeof MarketingContactRoute
  '/customers': typeof MarketingCustomersRoute
  '/help': typeof MarketingHelpRoute
  '/integrations': typeof MarketingIntegrationsRoute
  '/open': typeof MarketingOpenRoute
  '/oss-friends': typeof MarketingOssFriendsRoute
  '/pricing': typeof MarketingPricingRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/blog/': typeof MarketingBlogIndexRoute
  '/blog/category/$slug': typeof MarketingBlogCategorySlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof MarketingAboutRoute
  '/brand': typeof MarketingBrandRoute
  '/company': typeof MarketingCompanyRoute
  '/contact': typeof MarketingContactRoute
  '/customers': typeof MarketingCustomersRoute
  '/help': typeof MarketingHelpRoute
  '/integrations': typeof MarketingIntegrationsRoute
  '/open': typeof MarketingOpenRoute
  '/oss-friends': typeof MarketingOssFriendsRoute
  '/pricing': typeof MarketingPricingRoute
  '/': typeof MarketingIndexRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/blog': typeof MarketingBlogIndexRoute
  '/blog/category/$slug': typeof MarketingBlogCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/brand': typeof MarketingBrandRoute
  '/_marketing/company': typeof MarketingCompanyRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/customers': typeof MarketingCustomersRoute
  '/_marketing/help': typeof MarketingHelpRoute
  '/_marketing/integrations': typeof MarketingIntegrationsRoute
  '/_marketing/open': typeof MarketingOpenRoute
  '/_marketing/oss-friends': typeof MarketingOssFriendsRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
  '/_marketing/blog/category/$slug': typeof MarketingBlogCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand'
    | '/company'
    | '/contact'
    | '/customers'
    | '/help'
    | '/integrations'
    | '/open'
    | '/oss-friends'
    | '/pricing'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/brand'
    | '/company'
    | '/contact'
    | '/customers'
    | '/help'
    | '/integrations'
    | '/open'
    | '/oss-friends'
    | '/pricing'
    | '/'
    | '/blog/$slug'
    | '/blog'
    | '/blog/category/$slug'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/about'
    | '/_marketing/brand'
    | '/_marketing/company'
    | '/_marketing/contact'
    | '/_marketing/customers'
    | '/_marketing/help'
    | '/_marketing/integrations'
    | '/_marketing/open'
    | '/_marketing/oss-friends'
    | '/_marketing/pricing'
    | '/_marketing/'
    | '/_marketing/blog/$slug'
    | '/_marketing/blog/'
    | '/_marketing/blog/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/brand': {
      id: '/_marketing/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof MarketingBrandRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/company': {
      id: '/_marketing/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof MarketingCompanyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/customers': {
      id: '/_marketing/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof MarketingCustomersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help': {
      id: '/_marketing/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof MarketingHelpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/integrations': {
      id: '/_marketing/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof MarketingIntegrationsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/open': {
      id: '/_marketing/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof MarketingOpenRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/oss-friends': {
      id: '/_marketing/oss-friends'
      path: '/oss-friends'
      fullPath: '/oss-friends'
      preLoaderRoute: typeof MarketingOssFriendsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/category/$slug': {
      id: '/_marketing/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof MarketingBlogCategorySlugRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingBrandRoute: typeof MarketingBrandRoute
  MarketingCompanyRoute: typeof MarketingCompanyRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingCustomersRoute: typeof MarketingCustomersRoute
  MarketingHelpRoute: typeof MarketingHelpRoute
  MarketingIntegrationsRoute: typeof MarketingIntegrationsRoute
  MarketingOpenRoute: typeof MarketingOpenRoute
  MarketingOssFriendsRoute: typeof MarketingOssFriendsRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
  MarketingBlogCategorySlugRoute: typeof MarketingBlogCategorySlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingBrandRoute: MarketingBrandRoute,
  MarketingCompanyRoute: MarketingCompanyRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingCustomersRoute: MarketingCustomersRoute,
  MarketingHelpRoute: MarketingHelpRoute,
  MarketingIntegrationsRoute: MarketingIntegrationsRoute,
  MarketingOpenRoute: MarketingOpenRoute,
  MarketingOssFriendsRoute: MarketingOssFriendsRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
  MarketingBlogCategorySlugRoute: MarketingBlogCategorySlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
