/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingSlugRouteImport } from './routes/_marketing.$slug'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as MarketingBrandRouteImport } from './routes/_marketing.brand'
import { Route as MarketingCompanyRouteImport } from './routes/_marketing.company'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingCustomersRouteImport } from './routes/_marketing.customers'
import { Route as MarketingHelpRouteImport } from './routes/_marketing.help'
import { Route as MarketingIntegrationsRouteImport } from './routes/_marketing.integrations'
import { Route as MarketingInvestorRouteImport } from './routes/_marketing.investor'
import { Route as MarketingOpenRouteImport } from './routes/_marketing.open'
import { Route as MarketingOssFriendsRouteImport } from './routes/_marketing.oss-friends'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing.blog.index'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing.blog.$slug'
import { Route as MarketingBrandComponentsRouteImport } from './routes/_marketing.brand.components'
import { Route as MarketingCustomersSlugRouteImport } from './routes/_marketing.customers.$slug'
import { Route as MarketingIntegrationsSlugRouteImport } from './routes/_marketing.integrations.$slug'
import { Route as MarketingBlogCategorySlugRouteImport } from './routes/_marketing.blog.category.$slug'
import { Route as MarketingHelpArticleSlugRouteImport } from './routes/_marketing.help.article.$slug'
import { Route as MarketingHelpCategorySlugRouteImport } from './routes/_marketing.help.category.$slug'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSlugRoute = MarketingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBrandRoute = MarketingBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCompanyRoute = MarketingCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCustomersRoute = MarketingCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHelpRoute = MarketingHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingIntegrationsRoute = MarketingIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingInvestorRoute = MarketingInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOpenRoute = MarketingOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOssFriendsRoute = MarketingOssFriendsRouteImport.update({
  id: '/oss-friends',
  path: '/oss-friends',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBrandComponentsRoute =
  MarketingBrandComponentsRouteImport.update({
    id: '/components',
    path: '/components',
    getParentRoute: () => MarketingBrandRoute,
  } as any)
const MarketingCustomersSlugRoute = MarketingCustomersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingCustomersRoute,
} as any)
const MarketingIntegrationsSlugRoute =
  MarketingIntegrationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => MarketingIntegrationsRoute,
  } as any)
const MarketingBlogCategorySlugRoute =
  MarketingBlogCategorySlugRouteImport.update({
    id: '/blog/category/$slug',
    path: '/blog/category/$slug',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingHelpArticleSlugRoute =
  MarketingHelpArticleSlugRouteImport.update({
    id: '/article/$slug',
    path: '/article/$slug',
    getParentRoute: () => MarketingHelpRoute,
  } as any)
const MarketingHelpCategorySlugRoute =
  MarketingHelpCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => MarketingHelpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/$slug': typeof MarketingSlugRoute
  '/about': typeof MarketingAboutRoute
  '/brand': typeof MarketingBrandRouteWithChildren
  '/company': typeof MarketingCompanyRoute
  '/contact': typeof MarketingContactRoute
  '/customers': typeof MarketingCustomersRouteWithChildren
  '/help': typeof MarketingHelpRouteWithChildren
  '/integrations': typeof MarketingIntegrationsRouteWithChildren
  '/investor': typeof MarketingInvestorRoute
  '/open': typeof MarketingOpenRoute
  '/oss-friends': typeof MarketingOssFriendsRoute
  '/pricing': typeof MarketingPricingRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/brand/components': typeof MarketingBrandComponentsRoute
  '/customers/$slug': typeof MarketingCustomersSlugRoute
  '/integrations/$slug': typeof MarketingIntegrationsSlugRoute
  '/blog/': typeof MarketingBlogIndexRoute
  '/blog/category/$slug': typeof MarketingBlogCategorySlugRoute
  '/help/article/$slug': typeof MarketingHelpArticleSlugRoute
  '/help/category/$slug': typeof MarketingHelpCategorySlugRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof MarketingSlugRoute
  '/about': typeof MarketingAboutRoute
  '/brand': typeof MarketingBrandRouteWithChildren
  '/company': typeof MarketingCompanyRoute
  '/contact': typeof MarketingContactRoute
  '/customers': typeof MarketingCustomersRouteWithChildren
  '/help': typeof MarketingHelpRouteWithChildren
  '/integrations': typeof MarketingIntegrationsRouteWithChildren
  '/investor': typeof MarketingInvestorRoute
  '/open': typeof MarketingOpenRoute
  '/oss-friends': typeof MarketingOssFriendsRoute
  '/pricing': typeof MarketingPricingRoute
  '/': typeof MarketingIndexRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/brand/components': typeof MarketingBrandComponentsRoute
  '/customers/$slug': typeof MarketingCustomersSlugRoute
  '/integrations/$slug': typeof MarketingIntegrationsSlugRoute
  '/blog': typeof MarketingBlogIndexRoute
  '/blog/category/$slug': typeof MarketingBlogCategorySlugRoute
  '/help/article/$slug': typeof MarketingHelpArticleSlugRoute
  '/help/category/$slug': typeof MarketingHelpCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/$slug': typeof MarketingSlugRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/brand': typeof MarketingBrandRouteWithChildren
  '/_marketing/company': typeof MarketingCompanyRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/customers': typeof MarketingCustomersRouteWithChildren
  '/_marketing/help': typeof MarketingHelpRouteWithChildren
  '/_marketing/integrations': typeof MarketingIntegrationsRouteWithChildren
  '/_marketing/investor': typeof MarketingInvestorRoute
  '/_marketing/open': typeof MarketingOpenRoute
  '/_marketing/oss-friends': typeof MarketingOssFriendsRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/brand/components': typeof MarketingBrandComponentsRoute
  '/_marketing/customers/$slug': typeof MarketingCustomersSlugRoute
  '/_marketing/integrations/$slug': typeof MarketingIntegrationsSlugRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
  '/_marketing/blog/category/$slug': typeof MarketingBlogCategorySlugRoute
  '/_marketing/help/article/$slug': typeof MarketingHelpArticleSlugRoute
  '/_marketing/help/category/$slug': typeof MarketingHelpCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/brand'
    | '/company'
    | '/contact'
    | '/customers'
    | '/help'
    | '/integrations'
    | '/investor'
    | '/open'
    | '/oss-friends'
    | '/pricing'
    | '/blog/$slug'
    | '/brand/components'
    | '/customers/$slug'
    | '/integrations/$slug'
    | '/blog/'
    | '/blog/category/$slug'
    | '/help/article/$slug'
    | '/help/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/about'
    | '/brand'
    | '/company'
    | '/contact'
    | '/customers'
    | '/help'
    | '/integrations'
    | '/investor'
    | '/open'
    | '/oss-friends'
    | '/pricing'
    | '/'
    | '/blog/$slug'
    | '/brand/components'
    | '/customers/$slug'
    | '/integrations/$slug'
    | '/blog'
    | '/blog/category/$slug'
    | '/help/article/$slug'
    | '/help/category/$slug'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/$slug'
    | '/_marketing/about'
    | '/_marketing/brand'
    | '/_marketing/company'
    | '/_marketing/contact'
    | '/_marketing/customers'
    | '/_marketing/help'
    | '/_marketing/integrations'
    | '/_marketing/investor'
    | '/_marketing/open'
    | '/_marketing/oss-friends'
    | '/_marketing/pricing'
    | '/_marketing/'
    | '/_marketing/blog/$slug'
    | '/_marketing/brand/components'
    | '/_marketing/customers/$slug'
    | '/_marketing/integrations/$slug'
    | '/_marketing/blog/'
    | '/_marketing/blog/category/$slug'
    | '/_marketing/help/article/$slug'
    | '/_marketing/help/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/$slug': {
      id: '/_marketing/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof MarketingSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/brand': {
      id: '/_marketing/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof MarketingBrandRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/company': {
      id: '/_marketing/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof MarketingCompanyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/customers': {
      id: '/_marketing/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof MarketingCustomersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help': {
      id: '/_marketing/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof MarketingHelpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/integrations': {
      id: '/_marketing/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof MarketingIntegrationsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/investor': {
      id: '/_marketing/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof MarketingInvestorRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/open': {
      id: '/_marketing/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof MarketingOpenRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/oss-friends': {
      id: '/_marketing/oss-friends'
      path: '/oss-friends'
      fullPath: '/oss-friends'
      preLoaderRoute: typeof MarketingOssFriendsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/brand/components': {
      id: '/_marketing/brand/components'
      path: '/components'
      fullPath: '/brand/components'
      preLoaderRoute: typeof MarketingBrandComponentsRouteImport
      parentRoute: typeof MarketingBrandRoute
    }
    '/_marketing/customers/$slug': {
      id: '/_marketing/customers/$slug'
      path: '/$slug'
      fullPath: '/customers/$slug'
      preLoaderRoute: typeof MarketingCustomersSlugRouteImport
      parentRoute: typeof MarketingCustomersRoute
    }
    '/_marketing/integrations/$slug': {
      id: '/_marketing/integrations/$slug'
      path: '/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof MarketingIntegrationsSlugRouteImport
      parentRoute: typeof MarketingIntegrationsRoute
    }
    '/_marketing/blog/category/$slug': {
      id: '/_marketing/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof MarketingBlogCategorySlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help/article/$slug': {
      id: '/_marketing/help/article/$slug'
      path: '/article/$slug'
      fullPath: '/help/article/$slug'
      preLoaderRoute: typeof MarketingHelpArticleSlugRouteImport
      parentRoute: typeof MarketingHelpRoute
    }
    '/_marketing/help/category/$slug': {
      id: '/_marketing/help/category/$slug'
      path: '/category/$slug'
      fullPath: '/help/category/$slug'
      preLoaderRoute: typeof MarketingHelpCategorySlugRouteImport
      parentRoute: typeof MarketingHelpRoute
    }
  }
}

interface MarketingBrandRouteChildren {
  MarketingBrandComponentsRoute: typeof MarketingBrandComponentsRoute
}

const MarketingBrandRouteChildren: MarketingBrandRouteChildren = {
  MarketingBrandComponentsRoute: MarketingBrandComponentsRoute,
}

const MarketingBrandRouteWithChildren = MarketingBrandRoute._addFileChildren(
  MarketingBrandRouteChildren,
)

interface MarketingCustomersRouteChildren {
  MarketingCustomersSlugRoute: typeof MarketingCustomersSlugRoute
}

const MarketingCustomersRouteChildren: MarketingCustomersRouteChildren = {
  MarketingCustomersSlugRoute: MarketingCustomersSlugRoute,
}

const MarketingCustomersRouteWithChildren =
  MarketingCustomersRoute._addFileChildren(MarketingCustomersRouteChildren)

interface MarketingHelpRouteChildren {
  MarketingHelpArticleSlugRoute: typeof MarketingHelpArticleSlugRoute
  MarketingHelpCategorySlugRoute: typeof MarketingHelpCategorySlugRoute
}

const MarketingHelpRouteChildren: MarketingHelpRouteChildren = {
  MarketingHelpArticleSlugRoute: MarketingHelpArticleSlugRoute,
  MarketingHelpCategorySlugRoute: MarketingHelpCategorySlugRoute,
}

const MarketingHelpRouteWithChildren = MarketingHelpRoute._addFileChildren(
  MarketingHelpRouteChildren,
)

interface MarketingIntegrationsRouteChildren {
  MarketingIntegrationsSlugRoute: typeof MarketingIntegrationsSlugRoute
}

const MarketingIntegrationsRouteChildren: MarketingIntegrationsRouteChildren = {
  MarketingIntegrationsSlugRoute: MarketingIntegrationsSlugRoute,
}

const MarketingIntegrationsRouteWithChildren =
  MarketingIntegrationsRoute._addFileChildren(
    MarketingIntegrationsRouteChildren,
  )

interface MarketingRouteChildren {
  MarketingSlugRoute: typeof MarketingSlugRoute
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingBrandRoute: typeof MarketingBrandRouteWithChildren
  MarketingCompanyRoute: typeof MarketingCompanyRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingCustomersRoute: typeof MarketingCustomersRouteWithChildren
  MarketingHelpRoute: typeof MarketingHelpRouteWithChildren
  MarketingIntegrationsRoute: typeof MarketingIntegrationsRouteWithChildren
  MarketingInvestorRoute: typeof MarketingInvestorRoute
  MarketingOpenRoute: typeof MarketingOpenRoute
  MarketingOssFriendsRoute: typeof MarketingOssFriendsRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
  MarketingBlogCategorySlugRoute: typeof MarketingBlogCategorySlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingSlugRoute: MarketingSlugRoute,
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingBrandRoute: MarketingBrandRouteWithChildren,
  MarketingCompanyRoute: MarketingCompanyRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingCustomersRoute: MarketingCustomersRouteWithChildren,
  MarketingHelpRoute: MarketingHelpRouteWithChildren,
  MarketingIntegrationsRoute: MarketingIntegrationsRouteWithChildren,
  MarketingInvestorRoute: MarketingInvestorRoute,
  MarketingOpenRoute: MarketingOpenRoute,
  MarketingOssFriendsRoute: MarketingOssFriendsRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
  MarketingBlogCategorySlugRoute: MarketingBlogCategorySlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
