/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ControlRoomRouteImport } from './routes/control-room'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth.two-factor'
import { Route as AffiliateIndexRouteImport } from './routes/affiliate/index'
import { Route as AffiliateApplyRouteImport } from './routes/affiliate/apply'
import { Route as AffiliateDashboardRouteImport } from './routes/affiliate/dashboard'
import { Route as AffiliateOnboardingRouteImport } from './routes/affiliate/onboarding'
import { Route as BuilderIndexRouteImport } from './routes/builder/index'
import { Route as ControlRoomIndexRouteImport } from './routes/control-room/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ControlRoomAffiliatesIndexRouteImport } from './routes/control-room/affiliates/index'
import { Route as ControlRoomPeopleIndexRouteImport } from './routes/control-room/people/index'
import { Route as ControlRoomSettingsIndexRouteImport } from './routes/control-room/settings/index'
import { Route as ControlRoomWorkspacesIndexRouteImport } from './routes/control-room/workspaces/index'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard/billing/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardWorkspacesIndexRouteImport } from './routes/dashboard/workspaces/index'
import { Route as PreviewTokenIndexRouteImport } from './routes/preview/$token/index'
import { Route as ControlRoomWorkspacesWorkspaceIdIndexRouteImport } from './routes/control-room/workspaces/$workspaceId/index'
import { Route as DashboardProjectsIdIndexRouteImport } from './routes/dashboard/projects/$id/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomRoute = ControlRoomRouteImport.update({
  id: '/control-room',
  path: '/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AffiliateIndexRoute = AffiliateIndexRouteImport.update({
  id: '/affiliate/',
  path: '/affiliate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateApplyRoute = AffiliateApplyRouteImport.update({
  id: '/affiliate/apply',
  path: '/affiliate/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDashboardRoute = AffiliateDashboardRouteImport.update({
  id: '/affiliate/dashboard',
  path: '/affiliate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateOnboardingRoute = AffiliateOnboardingRouteImport.update({
  id: '/affiliate/onboarding',
  path: '/affiliate/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/builder/',
  path: '/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomIndexRoute = ControlRoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRoomRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomAffiliatesIndexRoute =
  ControlRoomAffiliatesIndexRouteImport.update({
    id: '/affiliates/',
    path: '/affiliates/',
    getParentRoute: () => ControlRoomRoute,
  } as any)
const ControlRoomPeopleIndexRoute = ControlRoomPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => ControlRoomRoute,
} as any)
const ControlRoomSettingsIndexRoute =
  ControlRoomSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ControlRoomRoute,
  } as any)
const ControlRoomWorkspacesIndexRoute =
  ControlRoomWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => ControlRoomRoute,
  } as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkspacesIndexRoute =
  DashboardWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const PreviewTokenIndexRoute = PreviewTokenIndexRouteImport.update({
  id: '/$token/',
  path: '/$token/',
  getParentRoute: () => PreviewRoute,
} as any)
const ControlRoomWorkspacesWorkspaceIdIndexRoute =
  ControlRoomWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => ControlRoomRoute,
  } as any)
const DashboardProjectsIdIndexRoute =
  DashboardProjectsIdIndexRouteImport.update({
    id: '/projects/$id/',
    path: '/projects/$id/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof AuthRouteWithChildren
  '/control-room': typeof ControlRoomRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/affiliate/apply': typeof AffiliateApplyRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/onboarding': typeof AffiliateOnboardingRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/control-room/': typeof ControlRoomIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/control-room/affiliates/': typeof ControlRoomAffiliatesIndexRoute
  '/control-room/people/': typeof ControlRoomPeopleIndexRoute
  '/control-room/settings/': typeof ControlRoomSettingsIndexRoute
  '/control-room/workspaces/': typeof ControlRoomWorkspacesIndexRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/workspaces/': typeof DashboardWorkspacesIndexRoute
  '/preview/$token/': typeof PreviewTokenIndexRoute
  '/control-room/workspaces/$workspaceId/': typeof ControlRoomWorkspacesWorkspaceIdIndexRoute
  '/dashboard/projects/$id/': typeof DashboardProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/affiliate/apply': typeof AffiliateApplyRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/onboarding': typeof AffiliateOnboardingRoute
  '/affiliate': typeof AffiliateIndexRoute
  '/builder': typeof BuilderIndexRoute
  '/control-room': typeof ControlRoomIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/control-room/affiliates': typeof ControlRoomAffiliatesIndexRoute
  '/control-room/people': typeof ControlRoomPeopleIndexRoute
  '/control-room/settings': typeof ControlRoomSettingsIndexRoute
  '/control-room/workspaces': typeof ControlRoomWorkspacesIndexRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesIndexRoute
  '/preview/$token': typeof PreviewTokenIndexRoute
  '/control-room/workspaces/$workspaceId': typeof ControlRoomWorkspacesWorkspaceIdIndexRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/control-room': typeof ControlRoomRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/affiliate/apply': typeof AffiliateApplyRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/onboarding': typeof AffiliateOnboardingRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/control-room/': typeof ControlRoomIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/control-room/affiliates/': typeof ControlRoomAffiliatesIndexRoute
  '/control-room/people/': typeof ControlRoomPeopleIndexRoute
  '/control-room/settings/': typeof ControlRoomSettingsIndexRoute
  '/control-room/workspaces/': typeof ControlRoomWorkspacesIndexRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/workspaces/': typeof DashboardWorkspacesIndexRoute
  '/preview/$token/': typeof PreviewTokenIndexRoute
  '/control-room/workspaces/$workspaceId/': typeof ControlRoomWorkspacesWorkspaceIdIndexRoute
  '/dashboard/projects/$id/': typeof DashboardProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/control-room'
    | '/preview'
    | '/login'
    | '/reset-password'
    | '/two-factor'
    | '/affiliate/apply'
    | '/affiliate/dashboard'
    | '/affiliate/onboarding'
    | '/affiliate/'
    | '/builder/'
    | '/control-room/'
    | '/dashboard/'
    | '/onboarding/'
    | '/control-room/affiliates/'
    | '/control-room/people/'
    | '/control-room/settings/'
    | '/control-room/workspaces/'
    | '/dashboard/billing/'
    | '/dashboard/projects/'
    | '/dashboard/workspaces/'
    | '/preview/$token/'
    | '/control-room/workspaces/$workspaceId/'
    | '/dashboard/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/login'
    | '/reset-password'
    | '/two-factor'
    | '/affiliate/apply'
    | '/affiliate/dashboard'
    | '/affiliate/onboarding'
    | '/affiliate'
    | '/builder'
    | '/control-room'
    | '/dashboard'
    | '/onboarding'
    | '/control-room/affiliates'
    | '/control-room/people'
    | '/control-room/settings'
    | '/control-room/workspaces'
    | '/dashboard/billing'
    | '/dashboard/projects'
    | '/dashboard/workspaces'
    | '/preview/$token'
    | '/control-room/workspaces/$workspaceId'
    | '/dashboard/projects/$id'
  id:
    | '__root__'
    | '/dashboard'
    | '/_auth'
    | '/control-room'
    | '/preview'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/two-factor'
    | '/affiliate/apply'
    | '/affiliate/dashboard'
    | '/affiliate/onboarding'
    | '/affiliate/'
    | '/builder/'
    | '/control-room/'
    | '/dashboard/'
    | '/onboarding/'
    | '/control-room/affiliates/'
    | '/control-room/people/'
    | '/control-room/settings/'
    | '/control-room/workspaces/'
    | '/dashboard/billing/'
    | '/dashboard/projects/'
    | '/dashboard/workspaces/'
    | '/preview/$token/'
    | '/control-room/workspaces/$workspaceId/'
    | '/dashboard/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ControlRoomRoute: typeof ControlRoomRouteWithChildren
  PreviewRoute: typeof PreviewRouteWithChildren
  AffiliateApplyRoute: typeof AffiliateApplyRoute
  AffiliateDashboardRoute: typeof AffiliateDashboardRoute
  AffiliateOnboardingRoute: typeof AffiliateOnboardingRoute
  AffiliateIndexRoute: typeof AffiliateIndexRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room': {
      id: '/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof ControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/affiliate/': {
      id: '/affiliate/'
      path: '/affiliate'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AffiliateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/apply': {
      id: '/affiliate/apply'
      path: '/affiliate/apply'
      fullPath: '/affiliate/apply'
      preLoaderRoute: typeof AffiliateApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/dashboard': {
      id: '/affiliate/dashboard'
      path: '/affiliate/dashboard'
      fullPath: '/affiliate/dashboard'
      preLoaderRoute: typeof AffiliateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/onboarding': {
      id: '/affiliate/onboarding'
      path: '/affiliate/onboarding'
      fullPath: '/affiliate/onboarding'
      preLoaderRoute: typeof AffiliateOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/builder'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room/': {
      id: '/control-room/'
      path: '/'
      fullPath: '/control-room/'
      preLoaderRoute: typeof ControlRoomIndexRouteImport
      parentRoute: typeof ControlRoomRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room/affiliates/': {
      id: '/control-room/affiliates/'
      path: '/affiliates'
      fullPath: '/control-room/affiliates/'
      preLoaderRoute: typeof ControlRoomAffiliatesIndexRouteImport
      parentRoute: typeof ControlRoomRoute
    }
    '/control-room/people/': {
      id: '/control-room/people/'
      path: '/people'
      fullPath: '/control-room/people/'
      preLoaderRoute: typeof ControlRoomPeopleIndexRouteImport
      parentRoute: typeof ControlRoomRoute
    }
    '/control-room/settings/': {
      id: '/control-room/settings/'
      path: '/settings'
      fullPath: '/control-room/settings/'
      preLoaderRoute: typeof ControlRoomSettingsIndexRouteImport
      parentRoute: typeof ControlRoomRoute
    }
    '/control-room/workspaces/': {
      id: '/control-room/workspaces/'
      path: '/workspaces'
      fullPath: '/control-room/workspaces/'
      preLoaderRoute: typeof ControlRoomWorkspacesIndexRouteImport
      parentRoute: typeof ControlRoomRoute
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/workspaces/': {
      id: '/dashboard/workspaces/'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces/'
      preLoaderRoute: typeof DashboardWorkspacesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/preview/$token/': {
      id: '/preview/$token/'
      path: '/$token'
      fullPath: '/preview/$token/'
      preLoaderRoute: typeof PreviewTokenIndexRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/control-room/workspaces/$workspaceId/': {
      id: '/control-room/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/control-room/workspaces/$workspaceId/'
      preLoaderRoute: typeof ControlRoomWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof ControlRoomRoute
    }
    '/dashboard/projects/$id/': {
      id: '/dashboard/projects/$id/'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id/'
      preLoaderRoute: typeof DashboardProjectsIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardWorkspacesIndexRoute: typeof DashboardWorkspacesIndexRoute
  DashboardProjectsIdIndexRoute: typeof DashboardProjectsIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardWorkspacesIndexRoute: DashboardWorkspacesIndexRoute,
  DashboardProjectsIdIndexRoute: DashboardProjectsIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ControlRoomRouteChildren {
  ControlRoomIndexRoute: typeof ControlRoomIndexRoute
  ControlRoomAffiliatesIndexRoute: typeof ControlRoomAffiliatesIndexRoute
  ControlRoomPeopleIndexRoute: typeof ControlRoomPeopleIndexRoute
  ControlRoomSettingsIndexRoute: typeof ControlRoomSettingsIndexRoute
  ControlRoomWorkspacesIndexRoute: typeof ControlRoomWorkspacesIndexRoute
  ControlRoomWorkspacesWorkspaceIdIndexRoute: typeof ControlRoomWorkspacesWorkspaceIdIndexRoute
}

const ControlRoomRouteChildren: ControlRoomRouteChildren = {
  ControlRoomIndexRoute: ControlRoomIndexRoute,
  ControlRoomAffiliatesIndexRoute: ControlRoomAffiliatesIndexRoute,
  ControlRoomPeopleIndexRoute: ControlRoomPeopleIndexRoute,
  ControlRoomSettingsIndexRoute: ControlRoomSettingsIndexRoute,
  ControlRoomWorkspacesIndexRoute: ControlRoomWorkspacesIndexRoute,
  ControlRoomWorkspacesWorkspaceIdIndexRoute:
    ControlRoomWorkspacesWorkspaceIdIndexRoute,
}

const ControlRoomRouteWithChildren = ControlRoomRoute._addFileChildren(
  ControlRoomRouteChildren,
)

interface PreviewRouteChildren {
  PreviewTokenIndexRoute: typeof PreviewTokenIndexRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewTokenIndexRoute: PreviewTokenIndexRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ControlRoomRoute: ControlRoomRouteWithChildren,
  PreviewRoute: PreviewRouteWithChildren,
  AffiliateApplyRoute: AffiliateApplyRoute,
  AffiliateDashboardRoute: AffiliateDashboardRoute,
  AffiliateOnboardingRoute: AffiliateOnboardingRoute,
  AffiliateIndexRoute: AffiliateIndexRoute,
  BuilderIndexRoute: BuilderIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
